---
version: 2.1

orbs:
  trailing-whitespace: orbss/trailing-whitespace@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  trailing-whitespace:
    executor: trailing-whitespace/default
    steps:
      - checkout
      - trailing-whitespace/execute

  regression-tests:
    executor: trailing-whitespace/default
    steps:
      - checkout

      - run:
          name: Test trailing whitespace exit status handling
          command: bash tests/test-trailing-whitespace.sh

  negative-integration-test:
    executor: trailing-whitespace/default
    steps:
      - checkout

      - run:
          name: Run negative integration test
          command: bash tests/test-negative-integration.sh

workflows:
  test-deploy:
    jobs:
      - trailing-whitespace:
          filters: *filters

      - regression-tests:
          filters: *filters

      - negative-integration-test:
          filters: *filters

      - orb-tools/pack:
          filters: *filters

      - orb-tools/publish:
          orb-name: orbss/trailing-whitespace
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - negative-integration-test
            - regression-tests
            - trailing-whitespace
          context: CIRCLECI_ORBS
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
